snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/runner/ProcessRunner.java

This PR fixes issue when a build tool is not in env.PATH and configured via plugin properties.
Windows uses semicolon (`;`) as path separator and not colon (`;`).

fix: use correct path separator in windows environment

---

README.md
snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/properties/AuthButtonFieldEditor.java

This PR makes `Snyk API Token` text field editable.
This is a temporary workaround: we allow users to enter their API token and persist it when settings are saved.

fix: make API token textfield editable

---

snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/runner/ProcessRunner.java
snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/runner/SnykCliRunner.java
snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/views/DataProvider.java

This PR provides a fix for Windows users in case Eclipse is installed in a folder with whitespaces (e.g. `Program Files`).
How to use quotes in CMD -> https://ss64.com/nt/cmd.html

fix: use double quotes when creating win process

---

snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/properties/AuthButtonFieldEditor.java
snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/properties/PreferencesPage.java
snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/runner/Authenticator.java
snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/runner/ProcessRunner.java
snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/runner/SnykCliRunner.java
snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/views/DataProvider.java

This PR fixes issue with running 'auth' command if token was already provided.
Now we use Eclipse preferences only, so snyk CLI runs can use different settings (~/.config/configstore/snyk.json).

fix: provide token and custom endpoint via environment variables

---

snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/runner/SnykCliRunner.java

Eclipse installed via Homebrew has a whitespace in the path (`Eclipse Platform.app`), so we have to quote executable path and params as well.

fix: quote full path to executable and params

---

io.snyk.bin.win/build.properties

This PR fixes exception when Eclipse is installed under `Program Files` on Windows.

fix: don't set permissions for windows binary

---

CHANGELOG.md
plugin/src/main/java/io/snyk/languageserver/LsRuntimeEnvironment.java

macOS M1 reports an unexpected architecture (aarch64) which is not covered by the current arch to language server mapping. This PR fixes this.

fix: add additional arch mapping for LS download

---

.github/workflows/readme-sync.yml

Always use HEAD for image urls in readme sync to prevent bot detecting changes when it's only remote git head hash update.

fix: always use HEAD for image urls in readme sync

---

CHANGELOG.md
plugin/plugin.xml
plugin/src/main/java/io/snyk/languageserver/LsConfigurationUpdater.java

- don't shutdown LS when all associated files are closed, in order to preserve cached diagnostics for an hour
- mark retrieved diagnostics as `Snyk` instead of `Language Server`

fix: various fixes & improvements

---

CHANGELOG.md
plugin/src/main/java/io/snyk/eclipse/plugin/SnykStartup.java
plugin/src/main/java/io/snyk/eclipse/plugin/domain/ScanResult.java
plugin/src/main/java/io/snyk/eclipse/plugin/properties/PreferencesPage.java
plugin/src/main/java/io/snyk/eclipse/plugin/runner/ProcessRunner.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/DataProvider.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/MenuHandler.java
plugin/src/main/java/io/snyk/languageserver/LsRuntimeEnvironment.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java
tests/src/test/java/io/snyk/languageserver/LsRuntimeEnvironmentTest.java

Previously, multi-module projects were not supported, there was rudimentary support for maven. Now both parsing and displaying is working, if CLI reports a multi-module scenario.
Also, if the plugin finds more than one pom file, as before, it automatically does a multi-pom scan by automatically setting `--all-projects` for that scan.

fix: Parse and Display multi-module project findings in legacy view correctly

---

plugin/src/main/java/io/snyk/eclipse/plugin/SnykStartup.java
plugin/src/main/java/io/snyk/eclipse/plugin/utils/CliDownloader.java
plugin/src/main/java/io/snyk/languageserver/LsRuntimeEnvironment.java
plugin/src/main/java/io/snyk/languageserver/download/LsDownloader.java

- use proxy configuration from language server download in cli download
- correct environment population with proxy data
The CLI download in Eclipse should be removed in favor of relying on the CLI download from language server. For this to happen, we need to unify directories in a follow-up PR.

fix: proxy support

---

plugin/src/main/java/io/snyk/eclipse/plugin/utils/CliDownloader.java

If no proxy settings were configured, the plugin did not download the CLI. This PR should fix it.
Fixes Issue #57

fix: also allow CLI download, if no http proxy is configured (fixes #57)

---

CHANGELOG.md
plugin/src/main/java/io/snyk/eclipse/plugin/properties/preferences/Preferences.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java

To provide server controlled navigation, the `window/showDocument` message is needed. This PR adds support for it by implementing it. Next step is a PR to LSP4e to add it to the base plugin.
Navigation via code lenses possible through this PR.

feat: add support for `window/showDocument` request [ROAD-1012]

---

.github/workflows/readme-sync.yml

Fixes readme sync PR creation. `gh pr view` shows merged PRs as well in its output, thus failing if check. Replaced with https://cli.github.com/manual/gh_pr_list

fix: readme sync

---

CHANGELOG.md
plugin/src/main/java/io/snyk/languageserver/download/HttpClientFactory.java

Previously, downloads and API calls from Eclipse didn't work with custom CAs. Now those calls also respect the preference setting.

feat: add support for insecure CAs in HTTP calls

---

.github/workflows/readme-sync.yml

To prepare for planned docs restructuring, where the docs for IDE tools will now be nested under the /integrations/ path, it's necessary to adjust the `readme-sync` workflow to ensure docs are continually synced with the README.
- ~~[ ]  Tests added and all succeed~~ Not applicable
- ~~[ ] Linted~~ Not applicable
- ~~[ ] CHANGELOG.md updated~~ Not applicable
- ~~[ ] README.md updated, if user-facing~~ Not applicable

chore: update README sync workflow

---

.github/workflows/readme-sync.yml

A fast follow from #125. Due to an extra level in the folder hierarchy, we need to adjust our sed script slightly.
- ~~[ ]  Tests added and all succeed~~ Not applicable
- ~~[ ] Linted~~ Not applicable
- ~~[ ] CHANGELOG.md updated~~ Not applicable
- ~~[ ] README.md updated, if user-facing~~ Not applicable

chore: fix sed bug in readme sync

---

.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
feature/category.xml
feature/feature.xml
feature/pom.xml
plugin/META-INF/MANIFEST.MF
plugin/pom.xml
plugin/src/main/java/io/snyk/eclipse/plugin/properties/PreferencesPage.java
pom.xml
target-platform/pom.xml
target-platform/target-platform.target
tests/META-INF/MANIFEST.MF
tests/pom.xml
update-site/category.xml
update-site/pom.xml

Newer Eclipse and LSP4e versions depend on JDK 17. This PR creates a new version 2.1 of our plugin that supports and requires running with JDK 17 and synchronizes with upstream.

chore: unpin LSP4e, release 2.1 [HEAD-170]

---

CHANGELOG.md
plugin/plugin.xml
plugin/src/main/java/io/snyk/eclipse/plugin/SnykStartup.java
plugin/src/main/java/io/snyk/languageserver/LsConfigurationUpdater.java
plugin/src/main/java/io/snyk/languageserver/SnykLanguageServer.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java

The current plugin uses (by necessity) methods from LSP4e. Some of these have been removed and thus need a change in how to integrate. As the Eclipse LSP4e project is still in incubation, API changes may sometimes occur.
This corrects API usage and cleans up the integration with LSP4e, by fixing, changing and removing plugin workarounds.

chore: update plugin to compile against upstream LSP4e [HEAD-349]

---

CHANGELOG.md
plugin/src/main/java/io/snyk/languageserver/LsRuntimeEnvironment.java

Remove custom path when launching language server, so that the path inside language server relies on the given configuration.

fix: Remove custom path when launching language server

---

CHANGELOG.md
plugin/src/main/java/io/snyk/eclipse/plugin/utils/LsMetadataResponseHandler.java

Bumps protocol version to 11. Don't merge before a CLI including https://github.com/snyk/snyk-ls/pull/485 is available.

chore: bump LS Protocol version to 11 [IDE-236]

---

.github/workflows/readme-sync.yml

Docs sync didn't work anymore because the gitbook docs structure has changed. This PR adjusts the sync source URL to the correct one.
It works now - see here: [Synchronize Readme](https://github.com/snyk/snyk-eclipse-plugin/actions/runs/9284905759)

fix: eclipse docs path in sync

---

CHANGELOG.md
plugin/src/main/java/io/snyk/eclipse/plugin/runner/SnykCliRunner.java

Eclipse has functionality to generate ignores using the `.snyk` ignore file. At the moment, this works but the generated ignores is not being taken into account when running a scan. This is because of extra quotes that get added incorrectly to the ignore rule.
This PR removes the unnecessary quote when running the `snyk ignore` command.
When using the CLI this is how I generate ignores: `snyk ignore --id=SNYK-JS-MARKED-2342073`
I used https://github.com/snyk-labs/nodejs-goof to test.
There are 120 vulns without the ignore so I applied an ignore (I already had the one I tested earlier):
After the ignore was generated we don't get the ignored vuln showing up (there are 111 vulns):
Matches what the CLI returns too:
**note** I did have to restart the sandbox because it wouldn't recognise …

fix: don't use quotes when generating ignore

---

plugin/src/main/java/io/snyk/eclipse/plugin/wizards/SnykWizardConfigureAPIPage.java

chore: changed the label of the endpoint configuration field
Before it was only stating Single Tenant. Now it also includes Multi Tenant

chore: changed the label of the endpoint configuration field

---

CHANGELOG.md
plugin/src/main/java/io/snyk/eclipse/plugin/properties/preferences/Preferences.java
plugin/src/main/java/io/snyk/eclipse/plugin/wizards/SnykWizardConfigureAPIPage.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/messageObjects/HasAuthenticatedParam.java
target-platform/target-platform.target
tests/src/test/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClientTest.java

If `$/snyk.hasAuthenticated` transmits an API URL, this is saved in the settings.

feat: process endpoint from hasAuthenticated message [IDE-732]

---

.classpath
CHANGELOG.md
plugin/src/main/java/io/snyk/eclipse/plugin/SnykStartup.java
plugin/src/main/java/io/snyk/eclipse/plugin/analytics/AbstractAnalyticsEvent.java
plugin/src/main/java/io/snyk/eclipse/plugin/analytics/AnalyticsEvent.java
plugin/src/main/java/io/snyk/eclipse/plugin/analytics/AnalyticsSender.java
plugin/src/main/java/io/snyk/eclipse/plugin/properties/PreferencesPage.java
plugin/src/main/java/io/snyk/eclipse/plugin/properties/preferences/InMemoryPreferenceStore.java
plugin/src/main/java/io/snyk/eclipse/plugin/properties/preferences/Preferences.java
plugin/src/main/java/io/snyk/eclipse/plugin/wizards/SnykWizard.java
plugin/src/main/java/io/snyk/languageserver/LsConfigurationUpdater.java
plugin/src/main/java/io/snyk/languageserver/SnykLanguageServer.java
plugin/src/main/java/io/snyk/languageserver/download/LsBinaries.java
plugin/src/main/java/io/snyk/languageserver/download/LsVersionRequest.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java
tests/META-INF/MANIFEST.MF
tests/src/test/java/io/snyk/eclipse/plugin/runner/SnykCliRunnerTest.java
tests/src/test/java/io/snyk/languageserver/LsBaseTest.java
tests/src/test/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClientTest.java

- send Analytics Event "plugin installed" on first start up
- better and asynchronous startup & error handling
- increases protocol version to 17
🚨 whitespaces changes should be excluded from diff.

feat: add plugin installed event [IDE-736]

---

plugin/src/main/java/io/snyk/eclipse/plugin/domain/ProductConstants.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/SnykToolView.java
plugin/src/main/java/io/snyk/eclipse/plugin/wizards/SnykWizard.java
plugin/src/main/java/io/snyk/languageserver/CommandHandler.java
plugin/src/main/java/io/snyk/languageserver/LsConstants.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/messageObjects/scanResults/AdditionalData.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/messageObjects/scanResults/Issue.java
tests/src/test/java/io/snyk/languageserver/protocolextension/CommandHandlerTest.java

This PR adds a context menu to the tree. For issue nodes, Ignore & Monitor are enabled. For other nodes, only Monitor is enabled.
When clicking on the menu option, an action/job is started, that calls the CLI to ignore the issue or monitor the project. The monitored project is always the top-level project of the source file in the Eclipse workspace.

feat: add context menu actions [IDE-784]

---

plugin/src/main/java/io/snyk/eclipse/plugin/wizards/SnykWizardAuthenticatePage.java

Created color resources must be disposed after usage.

fix: color resource leak

---

plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/ContentRootNode.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/ProductTreeNode.java

feat: mark disabled product nodes as disabled

---

plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/ContentRootNode.java

Simple fix to prevent user-facing error when eclipse is started with no projects open. Note that we still don't refresh plugins when a project is opened - I'll raise a separate ticket for that.
Previously, if eclipse was opened without a project, the plugin would crash and the user would see a garbled view with no obvious way to recover. Now, the Snyk plugin loads correctly.
Before:
After:

fix: prevent npe and user-facing error when eclipse is loaded with no projects open [IDE-845]

---

CHANGELOG.md
plugin/src/main/java/io/snyk/eclipse/plugin/analytics/TaskProcessor.java
plugin/src/main/java/io/snyk/eclipse/plugin/html/BaseHtmlProvider.java
plugin/src/main/java/io/snyk/eclipse/plugin/html/StaticPageHtmlProvider.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/BaseBranchDialog.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/BrowserHandler.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/ISnykToolView.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/SnykToolView.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/SummaryBrowserHandler.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/handlers/BaseProductFilterHandler.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/handlers/CollapseTreeHandler.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/handlers/FilterNetNewIssuesHandler.java
plugin/src/main/java/io/snyk/eclipse/plugin/wizards/SnykWizardModel.java
plugin/src/main/java/io/snyk/languageserver/LsConstants.java
plugin/src/main/java/io/snyk/languageserver/ScanState.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/messageObjects/SummaryPanelParams.java
plugin/src/main/resources/ui/html/ScanSummaryInit.html

Done:
- New Summary Panel.
- Notification listener `$/snyk.scanSummary` that receives HTML as a string from Snyk Language Server, and applies it to the summary panal.
- functions for changing tabs, toggling between all issues and delta issues.
- Apply styling to the HTML from Snyk Language Server.
- Hook up new browser function to the HTML tabs from Snyk Language Server.
`new BrowserFunction(browser, "enableDelta")`  
- Delta base branch selection.
- Update the getSummaryInitHtml().
- Update styling for the HTML in the Summary Panel.

feat: summary panel [IDE-892]

---

.github/workflows/resource-check.yml
plugin/src/main/java/io/snyk/eclipse/plugin/html/BaseHtmlProvider.java
plugin/src/main/resources/ui/html/ScanSummaryInit.html

fix: update font scaling logic to not use hard coded values

---

CHANGELOG.md
feature/category.xml
feature/feature.xml
feature/pom.xml
plugin/META-INF/MANIFEST.MF
plugin/pom.xml
plugin/src/main/java/io/snyk/eclipse/plugin/Activator.java
plugin/src/main/java/io/snyk/eclipse/plugin/html/BaseHtmlProvider.java
plugin/src/main/java/io/snyk/eclipse/plugin/preferences/Preferences.java
plugin/src/main/java/io/snyk/eclipse/plugin/preferences/PreferencesPage.java
plugin/src/main/java/io/snyk/eclipse/plugin/preferences/TokenFieldEditor.java
plugin/src/main/java/io/snyk/eclipse/plugin/utils/SnykIcons.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/BaseTreeNode.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/IssueTreeNode.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/ProductTreeNode.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/RootNode.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/handlers/BaseHandler.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/handlers/EnableAllProductHandler.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/providers/TreeLabelProvider.java
plugin/src/main/java/io/snyk/eclipse/plugin/wizards/SnykWizard.java
pom.xml
target-platform/pom.xml
target-platform/target-platform.target
tests/META-INF/MANIFEST.MF
tests/pom.xml
tests/src/test/java/io/snyk/eclipse/plugin/properties/preferences/PreferencesTest.java
tests/src/test/java/io/snyk/languageserver/LsBaseTest.java
tests/src/test/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClientTest.java
update-site/category.xml
update-site/pom.xml

- Using Eclipse ImageRegistry to cache images, and make sure they are disposed of correctly.
- fixed preference defaults and migration from secure storage to normal storage
- bumped Eclipse version to 3.1.0
No handle problem with >60000 issues.

fix: make sure all images created are disposed

---

plugin/src/main/java/io/snyk/eclipse/plugin/utils/ResourceUtils.java

When loading images, put the input stream into an auto-closable block

fix: close image input stream

---

plugin/src/main/java/io/snyk/eclipse/plugin/preferences/PreferencesPage.java

In IDEs, you can configure a custom endpoint in order to target a custom region (e.g EU). The current description for this option is "Sets API endpoint to use for Snyk requests. Useful for custom Snyk setups. E.g. https://api.eu.snyk.io/.". With the recent platform changes, on OAuth using SSO, we automatically redirect to the right instance and that field does not need to be configured anymore.
Update
If you're using SSO (OAuth2), API endpoint configuration is automatic. Otherwise, for public regional instances, see the docs. For private instances, contact your team or account manager.

feat: Update Endpoint Description in Settings

---

CHANGELOG.md
plugin/src/main/java/io/snyk/eclipse/plugin/html/CodeHtmlProvider.java
plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/BrowserHandler.java
plugin/src/main/java/io/snyk/languageserver/LsConstants.java
plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java
tests/src/test/resources/code_issue_description.html

The IAW command is now implemented and ignore requests are sent to the Snyk Language Server.

feat: add support for IAW command

---

.github/pull_request_template.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
Contributor-Agreement.md

Updated CONTRIBUTING.md to clarify our expectations for changes and to ensure collaboration before work is done.
Added CODE_OF_CONDUCT.md and Contributor-Agreement.md. (Although the [`license/cla` check](https://cla-assistant.io/) will be enabled at a later date when we have time)
Updated the PR template to point to CONTRIBUTING.md and CODE_OF_CONDUCT.md.
- N/A
- N/A
- N/A
- N/A

docs: clarify pre-contribution asking [IDE-1240]
