snyk_eclipse_plugin/src/io/snyk/eclipse/plugin/runner/SnykCliRunner.java
This PR fixes issue with whitespaces in Maven subprojects.
=> fix: quote path to file during snyk test

README.md, info-catalog.yaml, install-instructions/README.md, io.snyk.feature/category.xml, io.snyk.feature/feature.xml, snyk_eclipse_plugin/OSGI-INF/l10n/bundle.properties
Renaming to Snyk Security - Code and Open Source Dependencies
=> refactor: rename snyk vulnerability scanner display name [ROAD-686]

CHANGELOG.md, plugin/src/main/java/io/snyk/eclipse/plugin/runner/ProcessRunner.java, plugin/src/main/java/io/snyk/eclipse/plugin/runner/SnykCliRunner.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/SnykView.java, tests/src/test/java/io/snyk/eclipse/plugin/runner/ProcessRunnerTest.java
The scan under Windows, using the Snyk View and legacy functionality didn't work anymore. This is fixed by updating the process builder launching the process. Also fixed the passing of optional parameters (organization & insecure)
=> fix: legacy scan under windows

.github/workflows/release.yml, CHANGELOG.md, plugin/src/main/java/io/snyk/eclipse/plugin/properties/Preferences.java, plugin/src/main/java/io/snyk/eclipse/plugin/properties/PreferencesPage.java
=> chore: enable telemetry by default, add timezone info to release version/tag

plugin/src/main/java/io/snyk/languageserver/SnykStreamConnectionProvider.java, plugin/src/main/java/io/snyk/languageserver/download/LsDownloader.java
Download was failing if no proxy definition found.
=> fix: also allow downloads of language server if no proxy defined

.github/workflows/readme-sync.yml
Enable automatic signing commits issued by actions bot for readme sync.
Example PR: https://github.com/snyk/snyk-eclipse-plugin/pull/65
=> feat: sign commits on docs sync [ROAD-931]

.github/workflows/readme-sync.yml
fixes the source location of the file to be synchronized
=> fix: sync correct README.md file

.github/workflows/readme-sync.yml
Fix Snyk Docs synchronisation.
=> fix: readme sync to main [ROAD-1104]

plugin/src/main/java/io/snyk/languageserver/LsConfigurationUpdater.java, tests/src/test/java/io/snyk/languageserver/LsConfigurationUpdaterTest.java
Add Integration name and version to the initialization options in LS
=> Add integration name to analytics [ROAD-1062]

CHANGELOG.md, plugin/src/main/java/io/snyk/languageserver/LsRuntimeEnvironment.java
_This PR should fix the proxy URL construction being incorrect._
=> fix: malformed proxy URL [ROAD-1202]

plugin/src/main/java/io/snyk/eclipse/plugin/wizards/SnykWizard.java
SnykWizard was triggering authentication and trust on finishing without checking the workspace for projects. This leads to a NPE, as our language server client is still uninitialized. LSP4e only initializes the language client and starts the language server, when a project / file is associated with the corresponding mime/media type.
This fix wraps authentication and trust into a condition, checking, if the workspace contains **accessible projects.**
=> fix: 🐛 NPE when finishing Snyk Wizard in empty workspace

plugin/src/main/java/io/snyk/languageserver/download/LsBinaries.java
Update expected LSP protocol version to 6
=> Update LS protocol version

CHANGELOG.md, plugin/src/main/java/io/snyk/languageserver/download/LsBinaries.java
=> chore: bump LS version

plugin/src/main/java/io/snyk/eclipse/plugin/runner/ProcessRunner.java, plugin/src/main/java/io/snyk/languageserver/LsRuntimeEnvironment.java
=> fix: remove unnecessary token related env variables

plugin/src/main/java/io/snyk/languageserver/download/LsBinaries.java
=> chore: protocol version 9 for LS

plugin/src/main/java/io/snyk/languageserver/download/LsBinaries.java
Increase to LS Protocol version 10
=> feat: increase language server version

.github/workflows/ci.yml, .github/workflows/release.yml
Use updated creds for releases
=> chore: use rotated creds [HEAD-387]

plugin/src/main/java/io/snyk/languageserver/LsRuntimeEnvironment.java, tests/src/test/java/io/snyk/languageserver/LsRuntimeEnvironmentTest.java
remove incorrect fix-up of custom paths
N/A
=> Fix: custom path for CLI

.github/workflows/ci.yml, CHANGELOG.md, plugin/plugin.xml, plugin/src/main/java/io/snyk/eclipse/plugin/SnykStartup.java, plugin/src/main/java/io/snyk/eclipse/plugin/properties/PreferencesPage.java, plugin/src/main/java/io/snyk/eclipse/plugin/properties/preferences/Preferences.java, plugin/src/main/java/io/snyk/eclipse/plugin/utils/FileDownloadResponseHandler.java, plugin/src/main/java/io/snyk/eclipse/plugin/utils/LsMetadataResponseHandler.java, plugin/src/main/java/io/snyk/languageserver/LsRuntimeEnvironment.java, plugin/src/main/java/io/snyk/languageserver/SnykLanguageServer.java, plugin/src/main/java/io/snyk/languageserver/download/LsBinaries.java, plugin/src/main/java/io/snyk/languageserver/download/LsDownloadRequest.java, plugin/src/main/java/io/snyk/languageserver/download/LsDownloader.java, plugin/src/main/java/io/snyk/languageserver/download/LsMetadata.java, plugin/src/main/java/io/snyk/languageserver/download/LsShaRequest.java, plugin/src/main/java/io/snyk/languageserver/download/LsVersionRequest.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java, tests/src/test/java/io/snyk/eclipse/plugin/properties/preferences/PreferencesTest.java, tests/src/test/java/io/snyk/languageserver/LsBaseTest.java, tests/src/test/java/io/snyk/languageserver/LsRuntimeEnvironmentTest.java, tests/src/test/java/io/snyk/languageserver/download/LsDownloadRequestTest.java, tests/src/test/java/io/snyk/languageserver/download/LsDownloaderTest.java, tests/src/test/java/io/snyk/languageserver/download/LsShaDownloadRequestTest.java
=> fix: revert base URL change

.editorconfig, .mvn/wrapper/maven-wrapper.properties, CHANGELOG.md, mvnw, mvnw.cmd, plugin/META-INF/MANIFEST.MF, plugin/build.properties, plugin/io.snyk.eclipse.plugin.eml, plugin/pom.xml, plugin/src/main/java/io/snyk/eclipse/plugin/properties/PreferencesPage.java, plugin/src/main/java/io/snyk/eclipse/plugin/properties/preferences/Preferences.java, plugin/src/main/java/io/snyk/eclipse/plugin/properties/preferences/SecurePreferenceStore.java, plugin/src/main/java/io/snyk/languageserver/LsConfigurationUpdater.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java, pom.xml, tests/META-INF/MANIFEST.MF, tests/pom.xml
Sometimes, automatic scanning is not wanted. To be able to decide whether to use automatic scanning (on start-up & save) or manual scanning via explicit mouse-click, this PR adds a setting to the settings catalogue.
=> feat: add setting for scan mode

.circleci/config.yml, .github/CODEOWNERS, catalog-info.yaml
=> chore: change codeowner to ide

CHANGELOG.md, plugin/src/main/java/io/snyk/eclipse/plugin/properties/PreferencesPage.java
=> fix: bug in snyk code enablement check in preferences [IDE-55]

.circleci/config.yml
=> chore: change prodsec orb to do minor/patch updates automatically

CHANGELOG.md, feature/category.xml, feature/feature.xml, info-catalog.yaml, update-site/category.xml
https://snyksec.atlassian.net/browse/IDE-189
This PR shortens the name of the plugin to just "Snyk Security"
This change is based on multiple complaints from the field and customers.
=> [IDE-189] fix: shortened plugin's name to just Snyk Security 

.github/workflows/release.yml
=> chore: use github action secret for sha verification

.github/upload-to-s3.sh, .github/workflows/ci.yml, .github/workflows/release.yml
=> fix: s3 publishing

CHANGELOG.md, README.md, plugin/src/main/java/io/snyk/languageserver/LsConfigurationUpdater.java, plugin/src/main/java/io/snyk/languageserver/download/LsBinaries.java
Increases the required protocol version to 12, and also adds it to the LS initialization.
=> feat: update required protocol version to 12 [IDE-426] [IDE-376]

.github/workflows/readme-sync.yml, README.md
=> docs: update sync & latest docs

.circleci/config.yml, .snyk
Add quality gates and .snyk ignore file for licensing issues, as we are using EPL. 
The scan performed ignores the `tests` module using the a mvn native comand. 
=> chore: add quality gates

plugin/src/main/java/io/snyk/languageserver/download/LsBinaries.java
=> chore: bump ls version protocol to 14

.github/workflows/release.yml
As we are going to align our stable releases with the CLI schedule, this is a first step to disable automated weekly release.
=> chore: modified Github action to release new stable versions manually

plugin/META-INF/MANIFEST.MF, plugin/OSGI-INF/l10n/bundle.properties, plugin/build.properties, plugin/io.snyk.eclipse.plugin.eml, plugin/pom.xml, plugin/src/main/java/io/snyk/eclipse/plugin/properties/PreferencesPage.java, plugin/src/main/java/io/snyk/eclipse/plugin/properties/TokenFieldEditor.java, plugin/src/main/java/io/snyk/eclipse/plugin/properties/preferences/Preferences.java, plugin/src/main/java/io/snyk/eclipse/plugin/runner/ProcessRunner.java, plugin/src/main/java/io/snyk/eclipse/plugin/runner/SnykCliRunner.java, plugin/src/main/java/io/snyk/eclipse/plugin/wizards/SnykWizard.java, plugin/src/main/java/io/snyk/eclipse/plugin/wizards/SnykWizardConfigureAPIPage.java, plugin/src/main/java/io/snyk/languageserver/LsConfigurationUpdater.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/ProgressManager.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java, tests/src/test/java/io/snyk/eclipse/plugin/properties/preferences/PreferencesTest.java, tests/src/test/java/io/snyk/eclipse/plugin/runner/ProcessRunnerTest.java, tests/src/test/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClientTest.java
Enables OAuth2 authentication as default. 
TODO: update jackson deps
=> feat: enable oauth2 as default

.circleci/config.yml, .github/workflows/ci.yml, CHANGELOG.md, target-platform/target-platform.target, tests/pom.xml
- update workflow to only sign builds on main.
- updated jackson binaries to 2.15.0 to mitigate security issue
=> fix: dont sign build on PR checks

plugin/src/main/java/io/snyk/eclipse/plugin/properties/preferences/Preferences.java, tests/src/test/java/io/snyk/languageserver/download/LsDownloadRequestTest.java, tests/src/test/java/io/snyk/languageserver/download/LsShaDownloadRequestTest.java
Switch download URL from static.snyk.io to downloads.snyk.io
=> chore: switch CLI download strategy

plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/handlers/StopScanHandler.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/ProgressManager.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java, tests/src/test/java/io/snyk/eclipse/plugin/views/snyktoolview/BaseTreeNodeTest.java, tests/src/test/java/io/snyk/languageserver/protocolextension/ProgressManagerTest.java, tests/src/test/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClientTest.java
=> fix: progress manager and tests

plugin/src/main/java/io/snyk/languageserver/SnykIssueCache.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java, tests/src/test/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClientTest.java
- add product node suffixes about the number of issues found
- fix NPE when triggering a scan after authentication
=> feat: add product node suffixes

plugin/src/main/java/io/snyk/eclipse/plugin/html/BaseHtmlProvider.java, plugin/src/main/java/io/snyk/eclipse/plugin/html/CodeHtmlProvider.java, plugin/src/main/java/io/snyk/eclipse/plugin/html/OssHtmlProvider.java, plugin/src/main/java/io/snyk/eclipse/plugin/html/StaticPageHtmlProvider.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/BrowserHandler.java
=> fix: run init js after load complete

plugin/src/main/java/io/snyk/languageserver/SnykIssueCache.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/messageObjects/scanResults/IssueComparator.java
=> fix: tree sorting for oss

plugin/src/main/java/io/snyk/eclipse/plugin/utils/ResourceUtils.java, plugin/src/main/java/io/snyk/eclipse/plugin/utils/SnykLogger.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/BaseTreeNode.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/ContentRootNode.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/FileTreeNode.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/ProductTreeNode.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/SnykToolView.java, plugin/src/main/java/io/snyk/languageserver/IssueCacheHolder.java, plugin/src/main/java/io/snyk/languageserver/SnykIssueCache.java, plugin/src/main/java/io/snyk/languageserver/download/LsDownloader.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java, tests/src/test/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClientTest.java
WIP:  Still sometimes displays issues on wrong node.
=> fix: use project path as cache root and display issues on right node

plugin/src/main/java/io/snyk/eclipse/plugin/SnykStartup.java, plugin/src/main/java/io/snyk/languageserver/LsConfigurationUpdater.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/SdkHelper.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/messageObjects/LsSdk.java, tests/src/test/java/io/snyk/eclipse/plugin/properties/preferences/PreferencesTest.java, tests/src/test/java/io/snyk/eclipse/plugin/runner/ProcessRunnerTest.java, tests/src/test/java/io/snyk/languageserver/LsBaseTest.java, tests/src/test/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClientTest.java
=> feat: provide configured jdk for java projects

plugin/src/main/java/io/snyk/eclipse/plugin/html/BaseHtmlProvider.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/BrowserHandler.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/ProductTreeNode.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java
=> feat: display error message [IDE-797]

plugin/META-INF/MANIFEST.MF, plugin/build.properties, plugin/io.snyk.eclipse.plugin.eml, plugin/src/main/java/io/snyk/eclipse/plugin/analytics/TaskProcessor.java, plugin/src/main/java/io/snyk/eclipse/plugin/html/BaseHtmlProvider.java, plugin/src/main/java/io/snyk/eclipse/plugin/html/CodeHtmlProvider.java, plugin/src/main/java/io/snyk/eclipse/plugin/html/IacHtmlProvider.java, plugin/src/main/java/io/snyk/eclipse/plugin/html/OssHtmlProvider.java, plugin/src/main/java/io/snyk/eclipse/plugin/html/StaticPageHtmlProvider.java, plugin/src/main/java/io/snyk/eclipse/plugin/properties/PreferencesPage.java, plugin/src/main/java/io/snyk/eclipse/plugin/utils/ResourceUtils.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/BrowserHandler.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/ContentRootNode.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/SnykToolView.java, plugin/src/main/java/io/snyk/eclipse/plugin/views/snyktoolview/providers/TreeLabelProvider.java, plugin/src/main/java/io/snyk/languageserver/IssueCacheHolder.java, plugin/src/main/java/io/snyk/languageserver/ScanState.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/ProgressManager.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/SdkHelper.java, plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java, tests/src/test/java/io/snyk/eclipse/plugin/properties/preferences/SecurePreferenceStoreTest.java, tests/src/test/java/io/snyk/languageserver/LsRuntimeEnvironmentTest.java, tests/src/test/java/io/snyk/languageserver/protocolextension/ProgressManagerTest.java, tests/src/test/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClientTest.java
See https://www.perplexity.ai/search/what-is-jrt-fs-jar-hzEHMqUFRsaCUN_w3yFfWw
=> fix: better jdk detection

plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java, tests/src/test/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClientTest.java
=> fix: get security and quality nodes if enabled

plugin/src/main/java/io/snyk/eclipse/plugin/preferences/Preferences.java, plugin/src/main/java/io/snyk/eclipse/plugin/properties/FolderConfigs.java, tests/src/test/java/io/snyk/eclipse/plugin/properties/preferences/PreferencesUtils.java
don't use public static global variable (be nice to sharks)
=> chore: adjust preference visibility, use setter

plugin/src/main/java/io/snyk/eclipse/plugin/html/BaseHtmlProvider.java
Adds the bubble color for data-flow bubbles.
=> chore: add css variable for data-flow bubble

feature/category.xml, feature/feature.xml, feature/pom.xml, plugin/META-INF/MANIFEST.MF, plugin/pom.xml, pom.xml, target-platform/pom.xml, tests/META-INF/MANIFEST.MF, tests/pom.xml, update-site/category.xml, update-site/pom.xml
=> chore: bump version to 3.0.0

plugin/src/main/java/io/snyk/languageserver/download/LsBinaries.java
=> chore: bump ls protocol version to 18

plugin/src/main/resources/ui/html/ScanSummaryInit.html
updated static html, added tag for `ideStyle`.
=> fix: updated static html

plugin/src/main/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClient.java, tests/src/test/java/io/snyk/languageserver/protocolextension/SnykExtendedLanguageClientTest.java
=> fix: homogenize info node texts [IDE-936]

plugin/src/main/resources/ui/html/ScanSummaryInit.html
The spinner is displayed while waiting for the LS to load.
- N/A - Couldn't see a linter for HTML/CSS
- N/A
- N/A
=> fix: Unsquish the loading spinner [IDE-1101]

plugin/src/main/java/io/snyk/languageserver/download/LsBinaries.java
=> chore: bump LS protocol version

CHANGELOG.md
Forgot changelog for IVO filtering moving to LS.
- N/A
- N/A
- N/A
=> docs: update changelog for IVOs filtering in LS [IDE-899]

feature/category.xml, feature/feature.xml, feature/pom.xml, plugin/META-INF/MANIFEST.MF, plugin/pom.xml, pom.xml, target-platform/pom.xml, tests/META-INF/MANIFEST.MF, tests/pom.xml, update-site/category.xml, update-site/pom.xml
Forgot to update the release version in the source files.
=> chore: update Eclipse plugin version

RELEASE.md
Added a release.md describing the release process steps.
=> docs: added a release md file [IDE-1224]

RELEASE.md
=> Docs: update release document [IDE-1224]

.github/workflows/readme-sync.yml
- N/A
- N/A
- N/A
- Automatically, hopefully.
=> chore: new README.md source path [IDE-1266]

feature/category.xml, feature/feature.xml, feature/pom.xml, plugin/META-INF/MANIFEST.MF, plugin/pom.xml, pom.xml, target-platform/pom.xml, tests/META-INF/MANIFEST.MF, tests/pom.xml, update-site/category.xml, update-site/pom.xml
=> chore: bump version
